CAD_ICONE_SOURCE = "static_files\images\icon.png"
ATUALIZAR_ICONE_SOURCE = r"static_files\images\atualizar.png"
DELETAR_ICONE_SOURCE = "static_files\images\deletar.png"
PESQUISAR_ICONE_SOURCE = "static_files\images\pesquisar.png"
RESETAR_ICONE_SOURCE = r"static_files\images\resetar.png"
SELECIONAR_ICONE_SOURCE = "static_files\images\selecionar.png"
